### ISSUE TITLE
Main problems with Openapi schema generation

### ISSUE THREAD

**Issue by HomaDev** [HackSoftware/Django-Styleguide#144]
@RadoRado I'm trying to connect drf_sectacular for auto schema generation, but I'm facing some problems.
Can you name the main of them that made you write the scheme by hands?

**Comment by RadoRado** [comment]
@HomaDev You might've stumbled upon this particular issue - https://github.com/HackSoftware/Django-Styleguide/issues/134

Can you check and confirm :thinking:

**Comment by HomaDev** [comment]
@RadoRado Yes, I'm facing this issue, don't know how I missed it. 
But I'm also interested in why you don't use auto-generation in your projects 
Or maybe it is information from 2021 and now it's irrelevant?

**Comment by RadoRado** [comment]
@HomaDev This is how we usually approach OpenAPI stuff:

1. We usually start with the schema, before we even have backend implemented, in order to do few iterations with the frontend, before any backend has been even developed.
2. And we tend to maintain that by hand, in a separate place.
3. Now, we do use automatic generation for the yml itself, it's that we don't use the output of that automatic generation for the final schema that gets deployed.

Reason being - it's very rare that all the APIs that we have should be consumed by a client.

That's why there's a proposal for a mixin in the issue above.

Again, if auto generation works good for you - feel free to do just that :raised_hands: 

Cheers!

**Comment by HomaDev** [comment]
Ok, thanks for an explanation

**Comment by HomaDev** [comment]
I haven't implemented that solution yet, but the schema works perfectly with `ref_name `, so I'm closing this issue

**Comment by RadoRado** [comment]
@HomaDev Cheers!
