### ISSUE TITLE
Differences in the service layer for the admin panel and API

### ISSUE THREAD

**Issue by devmitrandir** [HackSoftware/Django-Styleguide#162]
I have a function that is called through the API and the admin panel.
Now it is required to add additional logic if it is created only through the API.

Any suggestions?

I’m thinking...

```python
def post_create():
  ...

def post_create_via_api():
    instance = post_create()
    # send_email()   
    return instance

# Maybe
# def post_create_via_admin():
#   instance = post_create()
#   return instance
```

Or

```python
def post_create_and_send_mail():
  instance = post_create()
  # send_email()   
  return instance
```

**Comment by RadoRado** [comment]
@devmitrandir Hello :wave: 

I'd do the following:

I'll create a new class, just to hold a common namespace for the service, and will follow-up with 2 methods (I usually start with a classmethod, if there is no need to hold state in the class), where the suffixes are going to be `xxx_from_api` and `xxx_from_admin`

Now, if there's a good reason for having this particular difference in the product / domain, I'd try to avoid having `from_api` and `from_admin`, since those names are pretty vague.

One potential renaming would be:

`xxx_from_backoffice` and `xxx_from_public`.

Another approach would be to put the `_from_admin` and `_from_api` in the namesapce of the class (meaning - the name of the class) and have the same method:

```python
class ServiceForAdmin:
    @classmethod
    def some_action(cls):
        pass


class ServiceForApi:
    @classmethod
    def some_action(cls):
        pass
```

There is no "right" way here - so you'll have to see what best fits your needs :ok_hand: 

Let me know if this was helpful.

**Comment by RadoRado** [comment]
@devmitrandir This also works, yes :+1: 

Again -  there are no "right" solutions here - as long as this makes sense and the logic can be expressed via inheritance (meaning - you call the `super()` and then add additional things) - this is great.

Cheers!

**Comment by devmitrandir** [comment]
Thank you very much!
