### ISSUE TITLE
services and tasks import loop

### ISSUE THREAD

**Issue by klmjoi** [HackSoftware/Django-Styleguide#50]
Thanks for your great guide, inspired me a lot!

I'm a bit confused about two examples about services and tasks.

A. `app/services.py` via https://github.com/HackSoftware/Django-Styleguide#example-services
```python
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from django_styleguide.payments.selectors import get_items_for_user
from django_styleguide.payments.models import Item, Payment
from django_styleguide.payments.tasks import charge_payment


def buy_item(
    *,
    item: Item,
    user: User,
) -> Payment:
    if item in get_items_for_user(user=user):
        raise ValidationError(f'Item {item} already in {user} items.')

    payment = Payment.objects.create(
        item=item,
        user=user,
        successful=False
    )

    charge_payment.delay(payment_id=payment.id)

    return payment
```

B. `app/tasks.py` via https://github.com/HackSoftware/Django-Styleguide#celery

```python
from celery import shared_task

from project.app.services import some_service_name as service


@shared_task
def some_service_name(*args, **kwargs):
    service(*args, **kwargs)
```

In example A, services call Celey task to execute one background task. In example B, one task is `just another interface to our core logic - meaning - don't put business logic there.`.

However, if they live under same application, `services.py` imports tasks from `tasks.py` and vice vesa. It makes import loop.

**Question**:
Should we put normal tasks which are called by services in file `tasks.py` and create a new file `cron_tasks.py` for executing services from `services.py` periodically? Or I misunderstood.

**Comment by wencakisa** [comment]
Hi, @klmjoi 👋 . Thanks for flagging a problem and opening this issue. 🙏 

---

Typically, when we have this circular import issue with services & tasks - we import the service function **inside** the task function:

```python
@shared_task
def task_function(*args, **kwargs):
    from project.app.services import service_function

    service_function(*args, **kwargs)
```

This way, you prevent the circular import and everything works as expected.

---

We will definitely add a note about this in the style guide because it's a very common use case when you have this architecture. :v:

**Comment by klmjoi** [comment]
Thanks @wencakisa.

This workaround is good. However, is it anti-pattern, like PEP 8 (`Imports are always put at the top of the file`)?

Is it better to refactor `services.py` and `tasks.py` to avoid importing each other?

Thanks.

**Comment by wencakisa** [comment]
@klmjoi You're right.

We're violating PEP8 on very rare occasions - and this is one of them. Even if you're not using the architecture suggested by the style guide, you can still have the problem with files importing each other.

Of course, in the common case, this is a signal that the architecture needs to be tweaked a bit in order to avoid circular imports. As the style guide is dynamic and we keep on changing our perspective, we will discuss this and decide whether we need a separate file (as you proposed) where we import services & tasks or we can keep the architecture the same and use the `import` workaround.

---

As [Python's documentation says](https://docs.python.org/3/tutorial/modules.html#more-on-modules):

> It is customary but not required to place all import statements at the beginning of a module (or script, for that matter).

But this contradicts PEP8's rule.

We can discuss this further.

---

Cheers! :v:

**Comment by thommor** [comment]
The way we worked around this is to use Django's [import_string](https://docs.djangoproject.com/en/3.1/ref/utils/#django.utils.module_loading.import_string) utility function which works the same as importing the task inside the service function and doesn't break PEP8 or Black etc.

We have a simple util function, something like: 
```python
def get_task(task_name: str) -> Callable:
    return import_string(f'app.tasks.{task_name}')
```

Then in your service you can call:
```python
get_task('charge_payment').delay(payment_id=payment.id)
```

**Comment by wencakisa** [comment]
@thommor This is neat.

We will try this and decide whether to do it this way from now on, rather than using inline imports.

In the meantime, feel free to open a PR with as a proposal and label it with `Point of view` so we can forward the discussion there. 

Cheers! :raised_hands:
