### ISSUE TITLE
Question about: InputSerializer should always be a plain Serializer

### ISSUE THREAD

**Issue by jsandovalc** [HackSoftware/Django-Styleguide#53]
Hi,

Thanks for the styleguide. I have a question, what is the reason to indicate that the `InputSerializer` should always be a plain `Serializer`?.

**Comment by RadoRado** [comment]
@jsandovalc A plain `serializers.Serializer` makes the most sense since we want to avoid the side effects of a `ModelSerializer` saving an object to the database, but, of course, you can use whatever makes sense for you :+1: 

Again, the idea is to be clear about what's happening & to be consistent with the approach for those certain cases.

I'd like to see an example where you use a `ModelSerializer` as an `InputSerializer` :+1:

**Comment by jsandovalc** [comment]
@RadoRado you mean a `ModelSerializer` automatically saves an object to the database?. I understand that after the call to `is_valid()` you can call `save` in the `ModelSerializer` to store it, but it has to be explicitly called.

I made some quick tests and that seems to be the case.

I personally have not used `ModelSerializer` for the `InputSerializer`, but by checking PRs with a colleague, we noticed he did. His argument is that it's a kind of CRUD endpoint, so the advantage of using a `ModelSerializer` is that the set of fields are automatically created for you and the related fields get checked on the `is_valid(raise_exception=True)` step. After that, the service gets executed with the `validated_data`.

**Comment by RadoRado** [comment]
@jsandovalc If you are not using the `.save()` part of the model serializer, I personally see no reason to use it at all.

This is part of the philosophy to not use additional layers of abstraction, if you don't actually need them.

Cheers!
