### ISSUE TITLE
How do you handle ordering?

### ISSUE THREAD

**Issue by jsandovalc** [HackSoftware/Django-Styleguide#70]
Hi, and thanks for the great work with the styleguide.

I was wonderig how is the recommended way to handle ordering according to the styleguide. I see filtering and pagination is specified, but not ordering. Should it be handled as a query_param with the FilterSerializer? In that case, I guess it's just a param to be taken out inside the service and used for ordering.

Thanks again.

**Comment by martin056** [comment]
Hi, @jsandovalc Thanks for the question!

There are 2 general approaches here which depend on what do you use in your project.

Approach 1: Add a separate `OrderingSerializer` to your API that is responsible for the ordering. This serializer usually has only one field.
Approach 2: You can use the [OrderingFIlter](https://django-filter.readthedocs.io/en/stable/ref/filters.html#orderingfilter) from `django-filters`. If you take this approach the ordering field will be part of the FilterSerializer.

I'd personally recommend you to use the first solution because I find it more simple and straightforward.

Here is an example that follows the first approach:
```
class ExampleListApi(ApiErrorsMixin, TeacherApiAuthMixin, APIView):
    class OutputSerializer(serializers.Serializer):
        id = serializers.IntegerField()
        name = serializers.CharField()

    class Pagination(LimitOffsetPagination):
        default_limit = 10

    class FilterSerializer(serializers.Serializer):
        name = serializers.CharField(required=False, allow_null=False)

    class OrderSerializer(serializers.Serializer):
        order_by = serializers.CharField(required=False)

    def get(self, request):
        filter_serializer = self.FilterSerializer(data=request.query_params)
        filter_serializer.is_valid(raise_exception=True)

        order_serializer = self.OrderSerializer(data=request.query_params)
        order_serializer.is_valid(raise_exception=True)

        tracker_instance_section_groups = example_list(
            request.user,
            filters=filter_serializer.validated_data,
            order_by=order_serializer.validated_data.get('order_by'),
        )

        paginator = self.Pagination()
        paginated_data = paginator.paginate_queryset(tracker_instance_section_groups, request)

        enriched_data = example_list_enrich(paginated_data)

        data = self.OutputSerializer(enriched_data, many=True).data

        return paginator.get_paginated_response(data=data)


def example_list(*, user: User, filtres: dict = None, order_by: str = None):
    filters = filtres or {}
    order_by = order_by or 'created_at'

    # Selector logic using the filters and order_by here ...
```

**Comment by jsandovalc** [comment]
Thanks for your kind (and fast) answer. All of you make a great job mantaining the styleguide.

**Comment by RadoRado** [comment]
Closing for now :v:
