### ISSUE TITLE
Why don't use Managers for services and QuerySets for selectors?

### ISSUE THREAD

**Issue by HMaker** [HackSoftware/Django-Styleguide#73]
Hi, this project is a good initiative to incentive high quality software building with Django, but I wonder why procedural-like programming is used for services & selectors layer when Django itself uses an object-oriented approach with Managers and QuerySets.

**Comment by RadoRado** [comment]
@HMaker Hello :wave: 

The answer is simple:

Services & selectors usually span across multiple models & boundaries. They are more related to the business domain, rather than to a specific model.

That's why coupling things with your specific model managers & querysets does not look like a good idea to us.

That said, you can take an object oriented approach with your service & selectors. We've given examples with functions, because it's easier to grasp, but we have projects, where some of the services are complex enough, that they are entire Python modules, with additional separation of concerns within them.

The idea of the styleguide is to encourage you to find more boxes than what Django provides, so you can structure your app in a better way.

If you think you can achieve the same, within a given project, with managers & querysets - please do so :ok_hand:

**Comment by HMaker** [comment]
yes, when operations spans over multiple models we can use a command-like approach (known more as Use Cases) that can be either object oriented or procedural, advantage of object oriented is that it's easier to extend later.
