### ISSUE TITLE
Where to put a custom id property?

### ISSUE THREAD

**Issue by masdot** [HackSoftware/Django-Styleguide#77]
For my project I need a user defined id. I currently create this with a @property but I have a hard time with this because this property also queries previous records for ids like: 20210001, 20210002, (...), 20220001

Would you leave this as property or what would be your alternative?

**Comment by RadoRado** [comment]
@masdot :wave: 

Can you expand a little bit more - perhaps with an example of what you are trying to achieve, so I can help you better?

Cheers!

**Comment by masdot** [comment]
@RadoRado 🤝

Yes, of course! Sorry if I have expressed myself inaccurately.

I need some kind of custom ID or numbering for my project.  This needs to be built according to the scheme '<year><ascending number>'.

This numbering is based on the records, which means that the creation date of the record is the basis for generating the numbering. For example, the records in 2020 are 
> 20200001 - 202100563.

and in 2021
> 20210001, 20210002, ...

However, I see it somewhat critical to solve this numbering via a 
_@property_ since this probably affects the scalability.

**Comment by RadoRado** [comment]
@masdot Sorry for the late answer! Catching up with the issues.

This sounds more like a database field and not a property.

And in order to generate sequential numbers, you might want to look into some kind of table locking or using F expressions ( https://docs.djangoproject.com/en/3.2/ref/models/expressions/#f-expressions )

Especially if you want to search or sort by those ids.

If you need them just for visual purposes, then a `@property` would do.

Hope that helps!

**Comment by masdot** [comment]
Thank you! 🙏
